---
title: "Weather Analysis"
output: html_notebook
---

Understanding the correlation between weather on JSE.


# Import the data 
The historical weather data for varies parts of SA have been downloaded, accompanied with the movement of the JSE all shares index over the same period.
```{r}
# set working directory 
setwd("~/Desktop/Quanta_CS/analysis")

# import weather data
jhb = read.csv("../data/weather/johannesburg.csv")
ct = read.csv("../data/weather/capetown.csv")
dur = read.csv("../data/weather/durban.csv")
pta = read.csv("../data/weather/pretoria.csv")
blm = read.csv("../data/weather/Bloemfontein.csv")

# JSE data
jse = read.csv('../data/jse/JALSH.csv')
```

### Clean Stock Data
```{r}
library(tidyverse)
library(dplyr)

# clean data
jse$Price = as.numeric(gsub(",", "",jse$Price))
jse$Open = as.numeric(gsub(",", "",jse$Open))
jse$Low = as.numeric(gsub(",", "",jse$Low))
jse$High = as.numeric(gsub(",", "",jse$High))

# Volume 
jse$Vol. = gsub("M", "000000", jse$Vol.)
jse$Vol. = gsub("B", "000000000", jse$Vol.)
jse$Vol. = as.numeric(jse$Vol.)
jse$Vol.[which(jse$Vol. < 10)] = jse$Vol.[jse$Vol. < 10]*10000
jse$Vol.

# Date
jse$Date = as.Date(jse$Date, format="%b %d, %y")

# Keep: date, price & vol
jse = jse %>% select('Date', "Price", "Vol.")

# View Cleanup
head(jse)
```


### Clean Weather Data 
```{r}
library(ggplot2)

ggplot(jse, aes(x=Date, y=Price)) + geom_line(col='darkblue') + ggtitle("JSE All Shares Index")

```



````










